### ISSUE TITLE
Error when testing plugin with Tracks for Trackmate 

### ISSUE THREAD

**Issue by kkbrar** [nicost/spotIntensityAnalysis#1]
Hi, 

I was wondering you would be able to help me with the following errors I get when testing the plugin with Tracks for Trackmate as suggested on ImageJ description website. The errors are as follows: 

Exception in thread "Thread-5" java.lang.ClassCastException: [B cannot be cast to [S
	at edu.ucsf.valelab.spotintensityanalysis.algorithm.Utils.Average(Utils.java:55)
	at edu.ucsf.valelab.spotintensityanalysis.RunAnalysis.run(RunAnalysis.java:73)

Many thanks!

**Comment by nicost** [comment]
See: https://forum.image.sc/t/error-in-spot-intensity-analysis-in-fiji-plugin-not-running/74160/2
